### ISSUE TITLE
Postgres Connector

### ISSUE THREAD

**Issue by DavidPerich** [venice-framework/venice-python#17]
Will this break if the images are downloading for the first time? They would take longer take longer than 3 minutes to download. 

```

#!/bin/bash
sleep 3m && \
echo \
"{
  \"name\" : \"postgres_buses_upsert_bus_locations\",
  \"config\" : {
    \"connector.class\" : \"io.confluent.connect.jdbc.JdbcSinkConnector\",
     \"connection.url\": \"jdbc:postgresql://$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB\",
     \"connection.user\": \"$POSTGRES_USER\",
     \"connection.password\": \"$POSTGRES_PASSWORD\",
     \"topics\": \"$TOPIC_NAME\",
     \"auto.create\":\"true\",
     \"auto.evolve\":\"true\",
     \"insert.mode\": \"upsert\",
     \"pk.mode\": \"record_key\"
  }
```

**Comment by nantrinh** [comment]
I have changed it in the `dev` branch, which is waiting to be merged into master.

connector-init now waits for kafka-connect to start listening, then sleeps for 2 mins (need to fix this to check if topic exists first), before sending the POST request.

I did notice that I didn't add a depends_on to connector-init though, I'll do that now.
